### ISSUE TITLE
Cannot find node.dll

### ISSUE THREAD

**Issue by Vishal1419** [frankhale/electron-with-express#3] opened 2016-08-08 06:22 UTC
I have installed node, After  that I have followed the instructions to run this app. 

In step 3 it is mentioned that a copy of node.exe and node.dll should be copied in the root directory of project. So, I searched for Node.exe and Node.dll in the folder where I installed node.

I found Node.exe but I am unable to find node.dll. 

The problem here is when I run the app, I can see a window. But it has a round progressbar. I don't get any content in short.

**Comment by frankhale** [comment] 2016-08-08 17:04
I'll try to make it more clear in the README where and why you need these. Get the node.exe and node.lib from here:

64bit - https://nodejs.org/dist/v6.3.1/win-x64/ 
32bit - https://nodejs.org/dist/v6.3.1/win-x86/

**Comment by Vishal1419** [comment] 2016-08-08 19:53
Thank you. The issue is solved. But after that I got another issue.  I can't see the text below welcome. The size of my window is 800 x 600 or full-screen, in either case the size of  object#browser-plugin-1 is 300 x 150. Also, the heading "Express" is cut-down. Why is it so?

![electron-with-express](https://cloud.githubusercontent.com/assets/19953475/17493881/ce2d1bec-5dcf-11e6-9c25-9e94a540ecb9.jpg)

**Comment by frankhale** [comment] 2016-08-09 03:58
I'm not sure I understand what issue you are experiencing now

**Comment by jimwild** [comment] 2016-08-09 04:30
I'm having the same issue, any pointer to get this running OSX? The express-app runs fine stand alone but not when I start Electron. Just getting the spinning loader also.

```events.js:160 Uncaught Error: spawn node.exe ENOENT```

**Comment by frankhale** [comment] 2016-08-09 04:47
I don't have a Mac so I cannot test this

**Comment by jimwild** [comment] 2016-08-09 04:53
No worries. Obviously node.exe being called on a mac won't work. I'll see if I can find a workaround and let you know. Cheers

**Comment by jimwild** [comment] 2016-08-09 05:26
That was easier than I thought - for OSX/Linux just change **node.exe** to **node** in `index.html` line 49

```node = spawn("node.exe", ["./express-app/bin/www"], { cwd: process.cwd() }),```

**Comment by frankhale** [comment] 2016-08-09 05:28
@jimwild you rock!

**Comment by Vishal1419** [comment] 2016-08-09 08:57
@frankhale I am running windows. Can you please provide a working sample without clipping of body as shown in above image?

**Comment by frankhale** [comment] 2016-08-09 14:18
@Vishal1419 looks like the CSS to make the webview the size of the window isn't working in your case. I'll test today to see if I can reproduce this in the latest version of Electron.

**Comment by frankhale** [comment] 2016-08-09 14:48
@Vishal1419 I just tested on Windows 10 and I cannot reproduce the behavior that you are seeing with respect to the size of the webview. 

The following CSS should be kicking in for you:

```css
.fullSize {
        position: absolute;
        width: 100%;
        height: 100%;
        display: none;
        overflow: auto;
 }
```

The webview should be using the class which makes it the full size of the window:

```javascript
<webview id="expressApp" class="fullSize"></webview>
```

**Comment by frankhale** [comment] 2016-08-09 14:59
@Vishal1419 actually I can reproduce this. It looks like the webview does have the correct size, eg. it's being set to 100% width and height but the `object` that is inside the webview which contains the content isn't sized the same so the content is clipped like you see. I'll see what I can do to force the `object` inside the webview to be the full size of the window.

**Comment by frankhale** [comment] 2016-08-09 18:41
Needed to use flex layout. I guess this is a new thing added in recent versions of Electron. 

http://electron.atom.io/docs/api/web-view-tag/#css-styling-notes

This is fixed in commit 861d81d13012bdf5bc806723071a344f075df86c

**Closed by frankhale** 2016-08-09 18:41 UTC

**Comment by Vishal1419** [comment] 2016-08-10 06:55
I have tested it further. And I can see that initially webview is sized to 100% of the available size. And then when I change the size of the window, the size of webview (or components inside it) does not have a change in width. So, a responsive approach is needed here. I don't know how

**Comment by frankhale** [comment] 2016-08-10 14:03
The resizing of the webview should be fixed in commit 861d81d. I just checked and when resizing the webview and it's contents are correctly resized based on the size of the window.

**Comment by frankhale** [comment] 2016-08-10 14:26
Here is an animated gif showing resizing content is working as expected. 

![2016-08-10_10-25-14](https://cloud.githubusercontent.com/assets/190154/17557348/d73f29a8-5ee4-11e6-8a58-74fbf653422b.gif)

**Comment by Vishal1419** [comment] 2017-02-14 09:44
@frankhale Thank you very much
